### ISSUE TITLE
Sulfur add/remove/edit

### ISSUE THREAD

**Issue by Ashendale** [klikli-dev/theurgy#167]
**Is your feature request related to a problem? Please describe.**
Maybe a feature request, maybe I'm being dumb. I found the local and server-side config files for Theurgy. Only a total of 2 files. None allows me to add/edit materials that have more sulfurs.

**Describe the solution you'd like**
Manually changing what materials can be transmuted. Create's zinc was recognized and added, but I can't add Iesnium, for example.

**Additional context**
I perfectly understand this would break the mod balance, but just keep it off by default. It's just a suggestion.

**Comment by klikli-dev** [comment]
@Ashendale that is a good suggestion!
It would not be a config because that's not how recipes work any more, but it should be datapackable.

Currently what you can do on 1.20.1 is use the "generic" sulfur + nbt to create your own sulfurs simply by making it a recipe output.
However I would not recommend to go down that route as I am about to deprecate it, that is why it is not documented.

In the future new sulfurs can be added via kubejs, because kubejs allows to create new items on the fly (which generally mods, unless specifically set up to do that, should not).

This feature is already available on 1.20.4 via https://www.curseforge.com/minecraft/mc-mods/theurgy-kubejs

If there is interest I can look into backporting it to 1.20.1

All that said, the absolutely preferred way to handle new sulfurs is to give me a list of desired sulfurs and I will add them to the base mod - either with recipes if the balance supports it, or without recipes which opens it up for modpack makers.
This way other modpacks also profit from the new materials :)

**Comment by Ashendale** [comment]
Thanks for the quick reply, and thanks for the link.

Seeing quite a few mods going up to 1.20.4 so, in my opinion, it's not worth the hassle of backporting and maintaining several versions of the same mod.

The kubejs seems to be the ideal way of editing. Less of a headache for the mod dev, more options for the pack dev.
