### ISSUE TITLE
Vat fermentation/digestion automation

### ISSUE THREAD

**Issue by uhloin** [klikli-dev/theurgy#211]
**Is your feature request related to a problem? Please describe.**
"I'm always frustrated when [...]" I need to remove weapon and even secondary item to open/close fermentation/digestion vat.
"I'm always frustrated when [...]" I need to restart process manually.
"I'm always frustrated when [...]" I lost some production because the system is idle.

**Describe the solution you'd like**
No manual open/close mechanics, just move result of fermentation/digestion to hopper below vat when it's ready (even 1 item). Opened/closed textures may be used to show that process in the progress (closed) or the vat has not enough right ingredients for processing (opened).

Also it's better to have some traditional interface with slots in the all machines instead of put/get items by right clicks.

**Additional context**

**Comment by klikli-dev** [comment]
@uhloin that is a valid point, but the "icky" automation was chosen intentionally to make the switching between tiers more expensive in terms of time investment.

However, if you are on 1.21 then the book now shows a very simple automation example that effectively achieves exactly what you are looking for with just a redstone torch and some redstone dust. You just need a pipe or logistics extractor instead of a hopper, because the hopper is sensitive to adjacent redstone and won't extract.

**Comment by uhloin** [comment]
Ok, thank you, for explanation. It's a pity, I have 1.20.1 Could you attach a screenshot? Pleeeease :))

Below is my production line for Netherite ingots. I think may be it's already complex enough and expensive in terms of time (processes in the vats are very slow). It requires pipes from other mod and also 2 auto-farms for carrots and oak logs. Without those farms from Botany Pots it would be even more hard. 

Previously, I used auto-mining of Ancient Debris in the Occultism Dimensional Mineshaft. If you use Occultism, then you use also Theurgy, and Theurgy way is way harder, but for the sake of sport... :)

![theurgy](https://github.com/user-attachments/assets/9bf98dbe-b7d1-4417-aeb9-d0346caac67c)

**Comment by klikli-dev** [comment]
Ahh in 1.20.1 it does not work the same way (redstone support is limited there) 

This is how it works in 1.21, but it outputs a redstone signal, and a comparator signal which help:

![image](https://github.com/user-attachments/assets/0f35f165-8413-480f-b8f5-f990cc7d515d)
![image](https://github.com/user-attachments/assets/b5afba32-0699-4024-b91c-967843a9e876)

In 1.20.1 you can open/close the vat with redstone but due to the lack of feedback on the inventory contents you need either a)  a mod that can read inventories without comparator (e.g. integrated dynamics) or b) use a sort of timer to open/close the vats in intervals to insert/extract results

**Comment by klikli-dev** [comment]
I just checked if it is feasible to backport the redstone stuff to 1.20.1 but sadly it is not possible (too much changed, especially the change from forge -> neoforge) so I think your best bet on 1.20.1 is to go with the above:

> In 1.20.1 you can open/close the vat with redstone but due to the lack of feedback on the inventory contents you need either a) a mod that can read inventories without comparator (e.g. integrated dynamics) or b) use a sort of timer to open/close the vats in intervals to insert/extract results

**Comment by uhloin** [comment]
OK, at least, now I know the redstone works from side for digestion vat, probably, I will use some sort of timer next time. As I can see, 1.21 becomes very popular from mod-developers, but still I see only 10% of mods migrated from 1.20.1, so it's may be a bit early for a gamer to make step forward. In any case thank you for advices.

**Comment by klikli-dev** [comment]
I will close this for now - if issues remain on 1.21 please ping me and we'll discuss how to improve things
