### ISSUE TITLE
Flux particles buildup causing lag

### ISSUE THREAD

**Issue by tomascryogen** [klikli-dev/theurgy#226]
Hello.
Very nice mod. Thank you for your work.

When not near, particles from the Flux Emitters to the machines queue up until viewed and then render all at once.
Works as expected when near machines.

1. Set up Flux Emitters and machines
2. Have items being processed 
3. Go to other floors of the base or other rooms
4. Frame rate decreasing over time depending on nr of emitters  
5. Go back to the processing room
6. Single large burst of particle streams when entering the room and looking at emitters and machines

Particles should not be stored and rendered from operations when the player is not looking at or near machines.

Burst:
![image](https://github.com/user-attachments/assets/0ef62b92-5048-4950-8d1f-5ec22d3562a7)
Normal operation:
![image](https://github.com/user-attachments/assets/3486d0c8-b06d-4442-93f1-676395498a7b)

- Theurgy Version: 1.56.0
- OS:  Windows 11
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: [ATM10](https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/5807241)

Not sure if this was happening with the previous versions, as I only made the large setup recently.

**Comment by klikli-dev** [comment]
Thank you for reporting this, I noticed something off about the particle effects sometimes, but never had it to this extent and made the connection. I will look into what is going wrong there

**Comment by klikli-dev** [comment]
Hmm not sure how this is caused as I am already using the limit to only send the message to tracking players.

I think this might be due to another mod (or vanilla/neoforge performance optimization) not ticking entities out of view - which makes sense usually, but now causes the entities to all "wait" until they are being sent. 

I will add a small change to discard projectiles too far away from the player. This will probably improve but not fix the situation.
Please let me know after the next update if the issue persists to a degree that causes FPS drops, because there is one more optimization I can do, but it is a bit more heavy handed
