### ISSUE TITLE
Add rockbuds

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/theurgy#50]
- [ ] age models
  - [ ] multiple sizes
  - [ ] Flower on top before reaching max age
  - [ ] pop open when ripe
- [ ] used to grow crops
- [ ] should work like a crop: grow from a seed, then ripen, be removed upon harvest
  - [ ] drop a seed that contains correct nbt
  - [ ] drop harvest 
- [ ] datapack system to control output count
- [ ] render resulting item on ripe rockbud
- [ ] crafting: 
  - not grafted
  - either use alchemical sulfur of type makes it t2, or allow crafting without (makes it t1/t1.5)
  - could be crop in center and rocks around
  - might need to craft or obtain a rockbud seed first? 
- [ ] Datapack
  - [ ] Data loading
  - [ ] Data generation
  - [ ] Data sync 
- [ ] JEI
  - [ ] fillItemCategory
  - [ ] subtype interpreter
  - [ ] recipe category for output

**Comment by Churn3d** [comment]
Lavis ideas: 
* hoe gravel or stone to turn it into "farmland", wet with water, then coat with seedpaste
* Rockbuds are entities instead of blocks you can grow them on any stone surface
* Worming? ic2 vibes for weeding
* cross pollination with other crops to generate materials other then wheat using bees!
* Decorative rockbuds! Wild ones recoil if approached or you move near them (observer detectable if a block?) but well cultivated ones don't recoil unless touched.
* little glowing green dots start to appear around your crops if you grow a lot of them :D

**Comment by klikli-dev** [comment]
Doesn't really fit the new direction of the mod, so I am closing this.
The whole idea of rockbuds is not really necessary because the goal - obtaining more food - will be achievable using the theurgy apparatus once sulfurs are implemented for crops.
