### ISSUE TITLE
Porting to 1.18.1

### ISSUE THREAD

**Issue by ultixon** [klikli-dev/theurgy#57]
**Is your feature request related to a problem? Please describe.**
Ex. I'm always "frustrated" when all of the good mods remain on older versions.

**Describe the solution you'd like**
I know updating a mod is a slow and tedious process but I'd like to request Theurgy be updated to 1.18.1.

**Additional context**

**Comment by klikli-dev** [comment]
I understand the request and the frustration - that said, Theurgy in its current state will not update to 1.18. 
Theurgy is undergoing a (long term, due to limited time) rework, as I'm not happy with the way it works right now. 
As none of the current systems will survive into the remake I decided not to invest the time to update it, but rather make sure that the new version will be available at the latest MC version at the time it is ready for a first release.

**Comment by ultixon** [comment]
That is understandable. Thanks for your time!
